// Share button — copies text to clipboard or uses Web Share API
import { useState } from 'react'
import { motion } from 'framer-motion'
import { Share2, Check } from 'lucide-react'
import toast from 'react-hot-toast'

export default function ShareButton({ text, audioUrl, label = 'Share', style = {} }) {
  const [copied, setCopied] = useState(false)

  const share = async () => {
    const shareText = text ? text.slice(0, 300) + (text.length > 300 ? '...' : '') : ''
    const shareData = {
      title: 'Vortex Voice AI',
      text: shareText,
      url: window.location.href,
    }

    // Use native share sheet on mobile if available
    if (navigator.share && navigator.canShare?.(shareData)) {
      try {
        await navigator.share(shareData)
        return
      } catch { /* user cancelled */ }
    }

    // Fallback: copy to clipboard
    const toCopy = shareText
      ? `${shareText}\n\n— Generated by Vortex Voice AI\n${window.location.origin}`
      : window.location.href
    try {
      await navigator.clipboard.writeText(toCopy)
      setCopied(true)
      toast.success('Copied to clipboard!')
      setTimeout(() => setCopied(false), 2000)
    } catch {
      toast.error('Could not copy')
    }
  }

  return (
    <motion.button whileTap={{ scale: 0.9 }} onClick={share}
      style={{
        display: 'flex', alignItems: 'center', gap: 6,
        padding: '7px 14px', borderRadius: 10, border: '1px solid var(--border)',
        background: 'var(--glass)', cursor: 'pointer', fontSize: 12, fontWeight: 600,
        color: copied ? '#10b981' : 'var(--text2)', transition: 'color 0.2s',
        ...style
      }}>
      {copied ? <Check size={13} color="#10b981" /> : <Share2 size={13} />}
      {copied ? 'Copied!' : label}
    </motion.button>
  )
}
